version: '3.8'

services:
  activepieces:
    image: activepieces/activepieces:latest
    container_name: activepieces
    ports:
      - "8135:80"
    volumes:
      - activepieces:/root/.activepieces
    environment:
      - AP_QUEUE_MODE=MEMORY
      - AP_DB_TYPE=SQLITE3
      - AP_FRONTEND_URL=http://colossus:8135
    restart: unless-stopped


volumes:
  activepieces:
