version: '3'

services:
  snipeit:
    image: snipe/snipe-it
    ports:
      - "9090:80" # Replace with your desired port
    env_file:
      - /env/snipe.env # This file should contain all the necessary environment variables
    volumes:
      - snipe-vol:/var/lib/snipeit
    depends_on:
      - snipe-mysql

  snipe-mysql:
    image: mysql:5.6 # or another version if you prefer
    env_file:
      - /env/snipe-sql.env # MySQL related environment variables
    exopse:
      - "3306"
    volumes:
      - snipesql-vol:/var/lib/mysql

volumes:
  snipe-vol:
  snipesql-vol:
