version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8083:80/tcp"
      - "444:443/tcp"
    volumes:
      - 'pihole-etc:/etc/pihole'
      - 'pihole-dnsmasq:/etc/dnsmasq.d'
    # env fils
    env_file:
      - /env/pihole.env
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    env_file:
      - /env/homarr.env
    volumes:
      - 'homarr-configs:/app/data/configs'
      - 'homarr-icons:/app/public/icons'
      - 'homarr-data:/data'
    ports:
      - '80:7575'

  lldap:
    image: lldap/lldap:stable
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    env_file:
      - /env/lldap.env

volumes:
  pihole-etc:
  pihole-dnsmasq:
  homarr-configs:
  homarr-icons:
  homarr-data:
  lldap_data:
    driver: local
