version: '3'

services:
  sharelatex:
    restart: unless-stopped
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      - sharelatex-mongo
      - sharelatex-redis
    ports:
      - "8088:80"
    volumes:
      - sharelatex_data:/var/lib/sharelatex
    env_file:
      - /env/sharelatex.env

  sharelatex-mongo:
    restart: unless-stopped
    image: mongo:4.0
    container_name: sharelatex-mongo
    command: ["--replSet", "rs0"] # Configuring as a single-node replica set
    volumes:
      - sharelatex_mongo_data:/data/db

  sharelatex-redis:
    restart: unless-stopped
    image: redis:5
    container_name: sharelatex-redis
    volumes:
      - sharelatex_redis_data:/data

volumes:
  sharelatex_data:
  sharelatex_mongo_data:
  sharelatex_redis_data:
